version: '3'

volumes:
  postgres_data:
      driver: local

services:
  db_sv:
      image: postgres:9.5
      container_name: db_sv
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/
      environment:
        POSTGRES_DB_PORT: "5432"
        POSTGRES_DB_HOST: "localhost"
        POSTGRES_DB: db_sunview
        POSTGRES_USER: sunview
        POSTGRES_PASSWORD: sunview